baseURL = "https://xianghao9506.github.io/QuartetLab/"
languageCode = 'en-us'
title = "Quartet Lab"
theme = "PaperMod"

[params]
    env = "production"
    description = "DIY Electrostatic Headphone Amplifiers"
    ShowReadingTime = false
    ShowShareButtons = false
    defaultTheme = "auto"

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Products"
    url = "/products/"
    weight = 2

  [[menu.main]]
    name = "Gallery"
    url = "/gallery/"
    weight = 3

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 6
