baseURL = "https://xianghao9506.github.io/QuartetLab/"
languageCode = 'en-us'
title = "Quartet Lab"
theme = "PaperMod"

[params]
    env = "production"
    description = "DIY Electrostatic Headphone Amplifiers"
    ShowReadingTime = false
    ShowShareButtons = false
    defaultTheme = "auto"